java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    RUN_DB_MIGRATION_ON_STARTUP: true
    DB_HOST: "{{ .Release.Name }}-postgresql"
    DB_NAME: "{{ .Values.postgresql.auth.database}}"
    DB_USER: "{{ .Values.postgresql.auth.username}}"
    DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    DB_PORT: "5432"
    AZURE_MANAGED_IDENTITY_ENABLED: true
    AZURE_STORAGE_ACCOUNT_NAME: factsaaat
  postgresql:
    enabled: true
