-- Alter Area of Law Types to include information needed for frontend display of links etc
ALTER TABLE area_of_law_types
  ADD COLUMN IF NOT EXISTS external_link VARCHAR,
  ADD COLUMN IF NOT EXISTS external_link_cy VARCHAR,
  ADD COLUMN IF NOT EXISTS display_name VARCHAR,
  ADD COLUMN IF NOT EXISTS display_name_cy VARCHAR;

WITH csv(name, external_link, external_link_cy, display_name, display_name_cy) AS (
  VALUES
    ('Crime', NULL, NULL, NULL, 'Troseddu'),
    ('Adoption', 'https://www.gov.uk/child-adoption', 'https://www.gov.uk/child-adoption', NULL, 'Mabwysiadu'),
    ('Children', NULL, NULL, 'Childcare arrangements if you separate from your partner',
      'Trefniadau gofal plant os ydych yn gwahanu oddi wrth eich partner'),
    ('Divorce', 'https://www.gov.uk/divorce', 'https://www.gov.uk/divorce', NULL, 'Ysgariad'),
    ('Domestic violence', NULL, NULL, 'Domestic abuse', 'Cam-drin domestig'),
    ('Social security', 'https://www.gov.uk/tribunal/sscs', 'https://www.gov.uk/tribunal/sscs', 'Benefits',
      'Budd-daliadau'),
    ('Housing possession', 'https://www.gov.uk/evicting-tenants', 'https://www.gov.uk/evicting-tenants', 'Housing',
      'Tai'),
    ('Money claims', 'https://www.gov.uk/make-court-claim-for-money',
      'https://www.gov.uk/make-court-claim-for-money', NULL, 'Hawliadau am arian'),
    ('Bankruptcy', 'https://www.gov.uk/apply-for-bankruptcy', 'https://www.gov.uk/apply-for-bankruptcy', NULL,
      'Methdaliad'),
    ('High Court District Registry', NULL,
      NULL,
      'High Court cases – serious or high profile criminal or civil law cases',
      'Achosion yn yr Uchel Lys – achosion cyfraith droseddol neu gyfraith sifil difrifol neu sy’n cael cryn amlwgrwydd'),
    ('Civil partnership', 'https://www.gov.uk/end-civil-partnership', NULL, NULL, 'Partneriaeth sifil'),
    ('Immigration', 'https://www.gov.uk/tribunal/iac', 'https://www.gov.uk/tribunal/iac', 'Immigration and asylum',
      'Mewnfudo'),
    ('Employment', 'https://www.gov.uk/courts-tribunals/employment-tribunal',
      'https://www.gov.uk/courts-tribunals/employment-tribunal', 'Claims against employers',
      'Honiadau yn erbyn cyflogwyr'),
    ('Probate', 'https://www.gov.uk/wills-probate-inheritance', 'https://www.gov.uk/wills-probate-inheritance',
      NULL, 'Profiant'),
    ('Tax', 'https://www.gov.uk/tax-tribunal', 'https://www.gov.uk/tax-tribunal', NULL, 'Treth'),
    ('Forced marriage', 'https://www.gov.uk/apply-forced-marriage-protection-order',
      'https://www.gov.uk/apply-forced-marriage-protection-order', NULL, 'Priodas dan orfod'),
    ('FGM', 'https://www.gov.uk/government/collections/female-genital-mutilation',
      'https://www.gov.uk/government/collections/female-genital-mutilation',
      'Female Genital Mutilation', 'Anffurfio Organau Cenhedlu Benywod'),
    ('Single justice procedure', NULL, NULL, NULL, 'Y Weithdrefn Un Ynad'),
    ('High Court', NULL, NULL, NULL, 'Uchel Lys'),
    ('Court Of Appeal', NULL, NULL, NULL, 'Llys Apêl'),
    ('Financial Remedy', 'https://www.gov.uk/money-property-when-relationship-ends',
      NULL,
      'If you are making an application to settle your finances following a divorce (Financial Remedy), please refer to the guidance found here',
      'Os ydych chi’n gwneud cais i setlo eich materion ariannol yn dilyn ysgariad (Rhwymedi Ariannol), cyfeiriwch at y cyfarwyddyd sydd ar gael yma'),
    ('Business and Property',
      'https://www.judiciary.uk/you-and-the-judiciary/going-to-court/high-court/courts-of-the-chancery-division/the-business-and-property-courts-in-birmingham',
      NULL, NULL, 'Busnes ac Eiddo'),
    ('Civil', NULL,
      NULL,
      'Making an application to settle finances following a divorce or ending a civil partnership',
      'Gwneud cais i setlo materion ariannol yn dilyn ysgariad neu ddiweddu partneriaeth sifil'),
    ('Pathfinder – for Private Law Proceedings', NULL, NULL, 'Pathfinder – for Private Law Proceedings',
      'Cynllun Braenaru – ar gyfer Achosion Cyfraith Breifat'),
    ('Domestic Abuse Protection Order (DAPOs)',
      'https://www.gov.uk/guidance/domestic-abuse-protection-notices-dapns-and-domestic-abuse-protection-orders-dapos',
      'https://www.gov.uk/guidance/domestic-abuse-protection-notices-dapns-and-domestic-abuse-protection-orders-dapos',
      'Gorchymyn Diogelu rhag Cam-drin Domestig',
      NULL),
    ('Benefits', 'https://www.gov.uk/appeal-benefit-decision', 'https://www.gov.uk/appeal-benefit-decision', NULL,
      NULL)
)
UPDATE area_of_law_types a
SET external_link = COALESCE(a.external_link, csv.external_link),
    external_link_cy = COALESCE(a.external_link_cy, csv.external_link_cy),
    display_name = COALESCE(a.display_name, csv.display_name),
    display_name_cy = COALESCE(a.display_name_cy, csv.display_name_cy)
FROM csv
WHERE LOWER(a.name) = LOWER(csv.name);
