-- Alter Area of Law Types to include information needed for frontend display of links etc
ALTER TABLE area_of_law_types
  ADD COLUMN IF NOT EXISTS external_link VARCHAR,
  ADD COLUMN IF NOT EXISTS external_link_cy VARCHAR,
  ADD COLUMN IF NOT EXISTS external_link_desc VARCHAR,
  ADD COLUMN IF NOT EXISTS external_link_desc_cy VARCHAR,
  ADD COLUMN IF NOT EXISTS display_name VARCHAR,
  ADD COLUMN IF NOT EXISTS display_name_cy VARCHAR,
  ADD COLUMN IF NOT EXISTS display_external_link VARCHAR,
  ADD COLUMN IF NOT EXISTS alt_name VARCHAR,
  ADD COLUMN IF NOT EXISTS alt_name_cy VARCHAR;

WITH csv(name, external_link, external_link_desc, external_link_desc_cy, alt_name, alt_name_cy,
         display_name, display_name_cy, display_external_link, external_link_cy) AS (
  VALUES
    ('Crime', NULL, NULL, NULL, NULL, 'Troseddu', NULL, 'Troseddu', NULL, NULL),
    ('Adoption', 'https://www.gov.uk/child-adoption', 'Information about adopting a child',
      'Gwybodaeth ynglŷn â mabwysiadu plentyn', NULL, 'Mabwysiadu', NULL, 'Mabwysiadu',
      'https://www.gov.uk/child-adoption/applying-for-an-adoption-court-order',
      'https://www.gov.uk/child-adoption'),
    ('Children', NULL, NULL, NULL, 'Childcare arrangements if you separate from your partner',
      'Trefniadau gofal plant os ydych yn gwahanu oddi wrth eich partner',
      'Childcare arrangements if you separate from your partner',
      'Trefniadau gofal plant os ydych yn gwahanu oddi wrth eich partner',
      'https://www.gov.uk/looking-after-children-divorce', NULL),
    ('Divorce', 'https://www.gov.uk/divorce', 'Information about getting a divorce',
      'Gwybodaeth ynglŷn â gwneud cais am ysgariad', 'Divorce hearings', 'Gwrandawiadau ysgariad',
      NULL, 'Ysgariad', NULL, 'https://www.gov.uk/divorce'),
    ('Domestic violence', NULL, NULL, NULL, 'Domestic abuse', 'Cam-drin domestig',
      'Domestic abuse', 'Cam-drin domestig', 'https://www.gov.uk/injunction-domestic-violence', NULL),
    ('Social security', 'https://www.gov.uk/tribunal/sscs',
      'Information about the Social Security and Child Support Tribunal',
      'Gwybodaeth ynglŷn â''r tribiwnlys nawdd cymdeithasol a chynnal plant',
      'Benefits', 'Budd-daliadau', 'Benefits', 'Budd-daliadau',
      'https://www.gov.uk/appeal-benefit-decision', 'https://www.gov.uk/tribunal/sscs'),
    ('Housing possession', 'https://www.gov.uk/evicting-tenants', 'Information about evicting tenants',
      'Gwybodaeth ynglŷn â troi tenantiaid allan', 'Housing', 'Tai', 'Housing', 'Tai',
      NULL, 'https://www.gov.uk/evicting-tenants'),
    ('Money claims', 'https://www.gov.uk/make-court-claim-for-money',
      'Information about making a court claim for money',
      'Gwybodaeth ynglŷn â gwneud hawliad llys am arian', NULL, 'Hawliadau am arian',
      NULL, 'Hawliadau am arian', NULL, 'https://www.gov.uk/make-court-claim-for-money'),
    ('Bankruptcy', 'https://www.gov.uk/apply-for-bankruptcy', 'Information about applying for bankruptcy',
      'Gwybodaeth ynglŷn â gwneud cais am fethdaliad', NULL, 'Methdaliad', NULL, 'Methdaliad',
      'https://www.gov.uk/bankruptcy', 'https://www.gov.uk/apply-for-bankruptcy'),
    ('High Court District Registry', NULL, NULL, NULL,
      'High Court cases – serious or high profile criminal or civil law cases',
      'Achosion yn yr Uchel Lys – achosion cyfraith droseddol neu gyfraith sifil difrifol neu sy’n cael cryn amlwgrwydd',
      'High Court cases – serious or high profile criminal or civil law cases',
      'Achosion yn yr Uchel Lys – achosion cyfraith droseddol neu gyfraith sifil difrifol neu sy’n cael cryn amlwgrwydd',
      NULL, NULL),
    ('Civil partnership', 'https://www.gov.uk/end-civil-partnership',
      'Information about ending a civil partnership',
      'Gwybodaeth ynglŷn â diweddu partneriaeth sifil', NULL, 'Partneriaeth sifil',
      NULL, 'Partneriaeth sifil', NULL, NULL),
    ('Immigration', 'https://www.gov.uk/tribunal/iac',
      'Information about the Immigration and Asylum Tribunal',
      'Gwybodaeth ynglŷn â''r tribiwnlys mewnfudo a lloches',
      'Immigration and asylum', 'Mewnfudo', 'Immigration and asylum', 'Mewnfudo',
      'https://www.gov.uk/immigration-asylum-tribunal', 'https://www.gov.uk/tribunal/iac'),
    ('Employment', 'https://www.gov.uk/courts-tribunals/employment-tribunal',
      'Information about the Employment Tribunal',
      'Gwybodaeth ynglŷn â''r tribiwnlys cyflogaeth',
      'Claims against employers', 'Honiadau yn erbyn cyflogwyr',
      'Claims against employers', 'Honiadau yn erbyn cyflogwyr',
      'https://www.gov.uk/employment-tribunals',
      'https://www.gov.uk/courts-tribunals/employment-tribunal'),
    ('Probate', 'https://www.gov.uk/wills-probate-inheritance',
      'Information about wills and probate', 'Gwybodaeth ynglŷn ag ewyllysiau a profiant',
      NULL, 'Profiant', NULL, 'Profiant', 'https://www.gov.uk/applying-for-probate',
      'https://www.gov.uk/wills-probate-inheritance'),
    ('Tax', 'https://www.gov.uk/tax-tribunal', 'Information about tax tribunals',
      'Gwybodaeth am tribiwnlysoedd treth', NULL, 'Treth', NULL, 'Treth',
      NULL, 'https://www.gov.uk/tax-tribunal'),
    ('Forced marriage', 'https://www.gov.uk/apply-forced-marriage-protection-order',
      'Information about forced marriage protection orders',
      'Gwybodaeth ynglŷn â gorchmynion amddiffyn priodas dan orfod',
      NULL, 'Priodas dan orfod', NULL, 'Priodas dan orfod',
      NULL, 'https://www.gov.uk/apply-forced-marriage-protection-order'),
    ('FGM', 'https://www.gov.uk/government/collections/female-genital-mutilation',
      NULL, NULL, 'Female Genital Mutilation', 'Anffurfio Organau Cenhedlu Benywod',
      'Female Genital Mutilation', 'Anffurfio Organau Cenhedlu Benywod',
      NULL, 'https://www.gov.uk/government/collections/female-genital-mutilation'),
    ('Single justice procedure', NULL, NULL, NULL, NULL, 'Y Weithdrefn Un Ynad',
      NULL, 'Y Weithdrefn Un Ynad', NULL, NULL),
    ('High Court', NULL, NULL, NULL, NULL, 'Uchel Lys', NULL, 'Uchel Lys', NULL, NULL),
    ('Court Of Appeal', NULL, NULL, NULL, NULL, 'Llys Apêl', NULL, 'Llys Apêl', NULL, NULL),
    ('Financial Remedy', 'https://www.gov.uk/money-property-when-relationship-ends',
      NULL, NULL, NULL, 'Rhwymedi Ariannol',
      'If you are making an application to settle your finances following a divorce (Financial Remedy), please refer to the guidance found here',
      'Os ydych chi’n gwneud cais i setlo eich materion ariannol yn dilyn ysgariad (Rhwymedi Ariannol), cyfeiriwch at y cyfarwyddyd sydd ar gael yma',
      NULL, NULL),
    ('Business and Property',
      'https://www.judiciary.uk/you-and-the-judiciary/going-to-court/high-court/courts-of-the-chancery-division/the-business-and-property-courts-in-birmingham',
      NULL, NULL, NULL, 'Busnes ac Eiddo', NULL, 'Busnes ac Eiddo', NULL, NULL),
    ('Civil', NULL, NULL, NULL, NULL, 'Rhwymedi Ariannol',
      'Making an application to settle finances following a divorce or ending a civil partnership',
      'Gwneud cais i setlo materion ariannol yn dilyn ysgariad neu ddiweddu partneriaeth sifil',
      NULL, NULL)
)
UPDATE area_of_law_types a
SET external_link = COALESCE(a.external_link, csv.external_link),
    external_link_cy = COALESCE(a.external_link_cy, csv.external_link_cy),
    external_link_desc = COALESCE(a.external_link_desc, csv.external_link_desc),
    external_link_desc_cy = COALESCE(a.external_link_desc_cy, csv.external_link_desc_cy),
    display_name = COALESCE(a.display_name, csv.display_name),
    display_name_cy = COALESCE(a.display_name_cy, csv.display_name_cy),
    display_external_link = COALESCE(a.display_external_link, csv.display_external_link),
    alt_name = COALESCE(a.alt_name, csv.alt_name),
    alt_name_cy = COALESCE(a.alt_name_cy, csv.alt_name_cy)
FROM csv
WHERE LOWER(a.name) = LOWER(csv.name);
