UPDATE public.service_area SET sort_order = 1 WHERE name = 'Money claims';
UPDATE public.service_area SET sort_order = 2 WHERE name = 'Probate';
UPDATE public.service_area SET sort_order = 3 WHERE name = 'Housing';
UPDATE public.service_area SET sort_order = 4 WHERE name = 'Bankruptcy';
UPDATE public.service_area SET sort_order = 5 WHERE name = 'Benefits';
UPDATE public.service_area SET sort_order = 6 WHERE name = 'Claims against employers';
UPDATE public.service_area SET sort_order = 7 WHERE name = 'Tax';
UPDATE public.service_area SET sort_order = 8 WHERE name = 'Single Justice Procedure';
UPDATE public.service_area SET sort_order = 9 WHERE name = 'Divorce';
UPDATE public.service_area SET sort_order = 10 WHERE name = 'Civil partnership';
UPDATE public.service_area SET sort_order = 11 WHERE name = 'Financial remedy';
UPDATE public.service_area SET sort_order = 12 WHERE name = 'Forced marriage';
UPDATE public.service_area SET sort_order = 13 WHERE name = 'Childcare arrangements if you separate from your partner';
UPDATE public.service_area SET sort_order = 14 WHERE name = 'Adoption';
UPDATE public.service_area SET sort_order = 15 WHERE name = 'Female Genital Mutilation Protection Orders';
UPDATE public.service_area SET sort_order = 16 WHERE name = 'Domestic abuse';
UPDATE public.service_area SET sort_order = 17 WHERE name = 'Immigration and asylum';
UPDATE public.service_area SET sort_order = 18 WHERE name = 'Other criminal offences';
UPDATE public.service_area SET sort_order = 19 WHERE name = 'High Court district registry';
