-- ------------------------------------------
-- ------   Type data required for FaCT  ----
-- ------------------------------------------
-- Bulk seed local_authority_types from search_localauthority
INSERT INTO local_authority_types (id, name)
VALUES (gen_random_uuid(), 'Bolton Borough Council'),
  (gen_random_uuid(), 'Bury Borough Council'),
  (gen_random_uuid(), 'Doncaster Borough Council'),
  (gen_random_uuid(), 'North East Lincolnshire Council'),
  (gen_random_uuid(), 'North Lincolnshire Council'),
  (gen_random_uuid(), 'North Tyneside Borough Council'),
  (gen_random_uuid(), 'Blackpool Borough Council'),
  (gen_random_uuid(), 'City of York Council'),
  (gen_random_uuid(), 'East Riding of Yorkshire Council'),
  (gen_random_uuid(), 'Oldham Borough Council'),
  (gen_random_uuid(), 'Pembrokeshire Council'),
  (gen_random_uuid(), 'Swansea Council'),
  (gen_random_uuid(), 'Neath Port Talbot Council'),
  (gen_random_uuid(), 'Stockport Borough Council'),
  (gen_random_uuid(), 'Tameside Borough Council'),
  (gen_random_uuid(), 'Denbighshire Council'),
  (gen_random_uuid(), 'Bradford City Council'),
  (gen_random_uuid(), 'Hull City Council'),
  (gen_random_uuid(), 'Manchester City Council'),
  (gen_random_uuid(), 'Salford City Council'),
  (gen_random_uuid(), 'Trafford Borough Council'),
  (gen_random_uuid(), 'Barnet Borough Council'),
  (gen_random_uuid(), 'Brent Borough Council'),
  (gen_random_uuid(), 'Camden Borough Council'),
  (gen_random_uuid(), 'City of London Corporation'),
  (gen_random_uuid(), 'Ealing Borough Council'),
  (gen_random_uuid(), 'Greenwich Borough Council'),
  (gen_random_uuid(), 'Hackney Borough Council'),
  (gen_random_uuid(), 'Hammersmith and Fulham Borough Council'),
  (gen_random_uuid(), 'Islington Borough Council'),
  (gen_random_uuid(), 'Kensington and Chelsea Borough Council'),
  (gen_random_uuid(), 'Merton Borough Council'),
  (gen_random_uuid(), 'Newham Borough Council'),
  (gen_random_uuid(), 'Wandsworth Borough Council'),
  (gen_random_uuid(), 'Westminster City Council'),
  (gen_random_uuid(), 'Tower Hamlets Borough Council'),
  (gen_random_uuid(), 'Ceredigion Council'),
  (gen_random_uuid(), 'Cheshire East Council'),
  (gen_random_uuid(), 'Cheshire West and Chester Council'),
  (gen_random_uuid(), 'Herefordshire Council'),
  (gen_random_uuid(), 'Powys Council'),
  (gen_random_uuid(), 'Shropshire Council'),
  (gen_random_uuid(), 'Staffordshire County Council'),
  (gen_random_uuid(), 'Telford and Wrekin Council'),
  (gen_random_uuid(), 'Wigan Borough Council'),
  (gen_random_uuid(), 'Worcestershire County Council'),
  (gen_random_uuid(), 'Wrexham Council'),
  (gen_random_uuid(), 'Dudley Borough Council'),
  (gen_random_uuid(), 'Sandwell Borough Council'),
  (gen_random_uuid(), 'Walsall Borough Council'),
  (gen_random_uuid(), 'Wolverhampton City Council'),
  (gen_random_uuid(), 'Blaenau Gwent Council'),
  (gen_random_uuid(), 'Caerphilly Council'),
  (gen_random_uuid(), 'Gloucestershire County Council'),
  (gen_random_uuid(), 'Monmouthshire Council'),
  (gen_random_uuid(), 'Newport Council'),
  (gen_random_uuid(), 'Rhondda Cynon Taf Council'),
  (gen_random_uuid(), 'Torfaen Council'),
  (gen_random_uuid(), 'Bridgend Council'),
  (gen_random_uuid(), 'Cardiff Council'),
  (gen_random_uuid(), 'Merthyr Tydfil Council'),
  (gen_random_uuid(), 'Vale of Glamorgan Council'),
  (gen_random_uuid(), 'Carmarthenshire Council'),
  (gen_random_uuid(), 'Conwy Council'),
  (gen_random_uuid(), 'Gwynedd Council'),
  (gen_random_uuid(), 'Isle of Anglesey Council'),
  (gen_random_uuid(), 'Redbridge Borough Council'),
  (gen_random_uuid(), 'Southwark Borough Council'),
  (gen_random_uuid(), 'Halton Borough Council'),
  (gen_random_uuid(), 'Knowsley Borough Council'),
  (gen_random_uuid(), 'Liverpool City Council'),
  (gen_random_uuid(), 'St Helens Borough Council'),
  (gen_random_uuid(), 'Warrington Borough Council'),
  (gen_random_uuid(), 'Bracknell Forest Council'),
  (gen_random_uuid(), 'Hampshire County Council'),
  (gen_random_uuid(), 'Oxfordshire County Council'),
  (gen_random_uuid(), 'Reading Borough Council'),
  (gen_random_uuid(), 'West Berkshire Council'),
  (gen_random_uuid(), 'Wiltshire Council'),
  (gen_random_uuid(), 'Windsor and Maidenhead Council'),
  (gen_random_uuid(), 'Wokingham Borough Council'),
  (gen_random_uuid(), 'Slough Borough Council'),
  (gen_random_uuid(), 'Barnsley Borough Council'),
  (gen_random_uuid(), 'Rotherham Borough Council'),
  (gen_random_uuid(), 'Wakefield City Council'),
  (gen_random_uuid(), 'Lancashire County Council'),
  (gen_random_uuid(), 'Sefton Borough Council'),
  (gen_random_uuid(), 'Wirral Borough Council'),
  (gen_random_uuid(), 'Kent County Council'),
  (gen_random_uuid(), 'Medway Council'),
  (gen_random_uuid(), 'East Sussex County Council'),
  (gen_random_uuid(), 'Brighton and Hove City Council'),
  (gen_random_uuid(), 'West Sussex County Council'),
  (gen_random_uuid(), 'Northumberland County Council'),
  (gen_random_uuid(), 'Milton Keynes Council'),
  (gen_random_uuid(), 'Durham County Council'),
  (gen_random_uuid(), 'Gateshead Borough Council'),
  (gen_random_uuid(), 'Newcastle City Council'),
  (gen_random_uuid(), 'South Tyneside Borough Council'),
  (gen_random_uuid(), 'Sunderland City Council'),
  (gen_random_uuid(), 'Calderdale Borough Council'),
  (gen_random_uuid(), 'Kirklees Borough Council'),
  (gen_random_uuid(), 'Leeds City Council'),
  (gen_random_uuid(), 'Cumbria County Council'),
  (gen_random_uuid(), 'Blackburn with Darwen Borough Council'),
  (gen_random_uuid(), 'Darlington Borough Council'),
  (gen_random_uuid(), 'Hartlepool Borough Council'),
  (gen_random_uuid(), 'Middlesbrough Council'),
  (gen_random_uuid(), 'North Yorkshire County Council'),
  (gen_random_uuid(), 'Redcar and Cleveland Borough Council'),
  (gen_random_uuid(), 'Stockton-on-Tees Borough Council'),
  (gen_random_uuid(), 'Bath and North East Somerset Council'),
  (gen_random_uuid(), 'Bournemouth Borough Council'),
  (gen_random_uuid(), 'Bristol City Council'),
  (gen_random_uuid(), 'Cornwall Council'),
  (gen_random_uuid(), 'Devon County Council'),
  (gen_random_uuid(), 'Dorset County Council'),
  (gen_random_uuid(), 'Isle of Wight Council'),
  (gen_random_uuid(), 'Isles of Scilly Council'),
  (gen_random_uuid(), 'North Somerset Council'),
  (gen_random_uuid(), 'Plymouth City Council'),
  (gen_random_uuid(), 'Poole Borough Council'),
  (gen_random_uuid(), 'Portsmouth City Council'),
  (gen_random_uuid(), 'Somerset County Council'),
  (gen_random_uuid(), 'Southampton City Council'),
  (gen_random_uuid(), 'South Gloucestershire Council'),
  (gen_random_uuid(), 'Swindon Borough Council'),
  (gen_random_uuid(), 'Torbay Borough Council'),
  (gen_random_uuid(), 'Flintshire Council'),
  (gen_random_uuid(), 'Surrey County Council'),
  (gen_random_uuid(), 'Barking and Dagenham Borough Council'),
  (gen_random_uuid(), 'Bedford Borough Council'),
  (gen_random_uuid(), 'Bexley Borough Council'),
  (gen_random_uuid(), 'Bromley Council'),
  (gen_random_uuid(), 'Cambridgeshire County Council'),
  (gen_random_uuid(), 'Central Bedfordshire Council'),
  (gen_random_uuid(), 'Croydon Borough Council'),
  (gen_random_uuid(), 'Enfield Borough Council'),
  (gen_random_uuid(), 'Essex County Council'),
  (gen_random_uuid(), 'Haringey Borough Council'),
  (gen_random_uuid(), 'Harrow Borough Council'),
  (gen_random_uuid(), 'Havering Borough Council'),
  (gen_random_uuid(), 'Hertfordshire County Council'),
  (gen_random_uuid(), 'Hillingdon Borough Council'),
  (gen_random_uuid(), 'Hounslow Borough Council'),
  (gen_random_uuid(), 'Kingston upon Thames Borough Council'),
  (gen_random_uuid(), 'Lambeth Borough Council'),
  (gen_random_uuid(), 'Lewisham Borough Council'),
  (gen_random_uuid(), 'Luton Borough Council'),
  (gen_random_uuid(), 'Norfolk County Council'),
  (gen_random_uuid(), 'Peterborough City Council'),
  (gen_random_uuid(), 'Richmond upon Thames Borough Council'),
  (gen_random_uuid(), 'Rutland County Council'),
  (gen_random_uuid(), 'Southend-on-Sea Borough Council'),
  (gen_random_uuid(), 'Suffolk County Council'),
  (gen_random_uuid(), 'Sutton Borough Council'),
  (gen_random_uuid(), 'Thurrock Borough Council'),
  (gen_random_uuid(), 'Waltham Forest Borough Council'),
  (gen_random_uuid(), 'Derby City Council'),
  (gen_random_uuid(), 'Derbyshire County Council'),
  (gen_random_uuid(), 'Leicestershire County Council'),
  (gen_random_uuid(), 'Nottinghamshire County Council'),
  (gen_random_uuid(), 'Birmingham City Council'),
  (gen_random_uuid(), 'Coventry City Council'),
  (gen_random_uuid(), 'Solihull Borough Council'),
  (gen_random_uuid(), 'Stoke-on-Trent City Council'),
  (gen_random_uuid(), 'Warwickshire County Council'),
  (gen_random_uuid(), 'Leicester City Council'),
  (gen_random_uuid(), 'Lincolnshire County Council'),
  (gen_random_uuid(), 'Northamptonshire County Council'),
  (gen_random_uuid(), 'Nottingham City Council'),
  (gen_random_uuid(), 'Sheffield City Council'),
  (gen_random_uuid(), 'Rochdale Borough Council'),
  (gen_random_uuid(), 'Buckinghamshire Council');

-- Bulk seed contact_description_types from admin_contacttype
INSERT INTO contact_description_types (id, name, name_cy)
VALUES
  (gen_random_uuid(), 'Accessibility enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Administration', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Administrative Court appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Administrative Court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Administrative Court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Admiralty Court appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Admiralty Court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Admiralty Court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Adoption', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Asylum Support Tribunal enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Bail applications', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Bailiff enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Building facilities', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Business and Property Court appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Business and Property Court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Business and Property Court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Case progression', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Central London county court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Centralised Attachment of Earnings (CAPS)', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Chancery division appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Chancery division court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Chancery division enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Chancery division issues', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Chancery Masters appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Child arrangements', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Child maintenance', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Children in care', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Circuit Commercial Court appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Circuit Commercial Court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Circuit Commercial Court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Circuit Court appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Circuit Court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Circuit Court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Citizens Advice Witness Service', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Civil appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Civil court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Civil enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Commercial Court appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Commercial Court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Commercial Court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Companies winding up', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Confiscation enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'County court appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'County court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'County court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Court clerks', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Court of Appeal Civil Division', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Court of Appeal Criminal Division', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Court of Protection', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Criminal Injuries Compensation Tribunal enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Crown Court appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Crown Court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Crown Court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Debt respite scheme enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'District court appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'District court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'District court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Divorce enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Domestic violence remedy orders', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Employment Tribunal enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Enforcement enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Enforcement fine enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Family court appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Family court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Family court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Family private law', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Family public law', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Fee enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Female genital mutilation protection orders', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Finances', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Financial remedy during divorce', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Fine enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Fixed penalties', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Forced marriage protection orders', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'High Court appeals', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'High Court appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'High Court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'High Court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Immigration and Asylum appeals enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Immigration and Asylum Tribunal appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Immigration and Asylum Tribunal court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Immigration and Asylum Tribunal enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Insolvency and Companies Court appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Insolvency and Companies Court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Insolvency and Companies Court issues', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Insolvency and Companies Court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Issues', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Jury service', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'King''s Bench Division appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'King''s Bench Division court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'King''s Bench Division enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Legal aid', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'London Circuit Commercial Court appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'London Circuit Commercial Court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'London Circuit Commercial Court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Magistrates'' court appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Magistrates'' court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Magistrates'' court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Mediation appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Mediation enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Online civil money claims enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Orders and accounts', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Pay a fee', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Pay a fine', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Payments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Planning Court', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Possession', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Post court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Pre and post court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Pre court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Probate enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Registrar', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Registry enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Security', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Senior courts costs office', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Single Justice Procedures enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Social Security and Child Support benefit appeals enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Social Security and Child Support Tribunal enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Support Through Court', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Switchboard', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Technology and Construction Court appointments', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Technology and Construction Court enquiries', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Technology and Construction Court issues', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Technology and Construction Court lists', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Textphone', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Transcripts', 'CHANGE ME / NEED WELSH'),
  (gen_random_uuid(), 'Welsh language helpline', 'CHANGE ME / NEED WELSH');

-- Bulk seed opening_hour_types from admin_openingtype
INSERT INTO opening_hour_types (id, name, name_cy)
VALUES (gen_random_uuid(), 'Telephone enquiries answered', 'Oriau ateb ymholiadau dros y ffôn'),
 (gen_random_uuid(), 'Court open', 'Oriau agor y Llys'),
 (gen_random_uuid(), 'Tribunal open', 'Oriau agor y tribiwnlys'),
 (gen_random_uuid(), 'Telephone payments accepted', 'Derbynnir taliadau ffôn'),
 (gen_random_uuid(), 'Magistrates'' Court open', 'Llys Ynadon ar agor'),
 (gen_random_uuid(), 'Crown Court open', 'Llys y Goron ar agor'),
 (gen_random_uuid(), 'Family Court open', 'Llys Teulu ar agor'),
 (gen_random_uuid(), 'No counter service available', 'CHANGE ME / NEED WELSH'),
 (gen_random_uuid(), 'County Court open', 'Llys Sirol ar agor');

-- Bulk seed region from search_region
INSERT INTO region (id, name, country)
VALUES (gen_random_uuid(), 'Eastern', 'England'),
 (gen_random_uuid(), 'North West', 'England'),
 (gen_random_uuid(), 'North East', 'England'),
 (gen_random_uuid(), 'South East', 'England'),
 (gen_random_uuid(), 'South West', 'England'),
 (gen_random_uuid(), 'East Midlands', 'England'),
 (gen_random_uuid(), 'London', 'England'),
 (gen_random_uuid(), 'West Midlands', 'England'),
 (gen_random_uuid(), 'Yorkshire and the Humber', 'England'),
 (gen_random_uuid(), 'South Wales West', 'Wales'),
 (gen_random_uuid(), 'South Wales Central', 'Wales'),
 (gen_random_uuid(), 'South Wales East', 'Wales'),
 (gen_random_uuid(), 'Mid and West Wales', 'Wales'),
 (gen_random_uuid(), 'North Wales', 'Wales'),
 (gen_random_uuid(), 'Scotland', 'Scotland');

-- Bulk seed area_of_law_types from search_areaoflaw
INSERT INTO area_of_law_types (id, name, name_cy)
VALUES (gen_random_uuid(), 'Divorce', 'Divorce'),
 (gen_random_uuid(), 'Civil partnership', 'Civil partnership'),
 (gen_random_uuid(), 'High Court District Registry', 'High Court District Registry'),
 (gen_random_uuid(), 'Adoption', 'Adoption'),
 (gen_random_uuid(), 'Social security', 'Social security'),
 (gen_random_uuid(), 'Housing possession', 'Housing possession'),
 (gen_random_uuid(), 'Money claims', 'Money claims'),
 (gen_random_uuid(), 'Employment', 'Employment'),
 (gen_random_uuid(), 'Tax', 'Tax'),
 (gen_random_uuid(), 'Children', 'Children'),
 (gen_random_uuid(), 'Domestic violence', 'Domestic violence'),
 (gen_random_uuid(), 'Crime', 'Crime'),
 (gen_random_uuid(), 'Civil', 'Civil'),
 (gen_random_uuid(), 'Single justice procedure', 'Single justice procedure'),
 (gen_random_uuid(), 'High Court', 'High Court'),
 (gen_random_uuid(), 'Court Of Appeal', 'Court Of Appeal'),
 (gen_random_uuid(), 'Financial Remedy', 'Financial Remedy'),
 (gen_random_uuid(), 'Business and Property', 'Business and Property'),
 (gen_random_uuid(), 'Bankruptcy', 'Bankruptcy'),
 (gen_random_uuid(), 'Immigration', 'Immigration'),
 (gen_random_uuid(), 'Probate', 'Probate'),
 (gen_random_uuid(), 'Forced marriage', 'Forced marriage'),
 (gen_random_uuid(), 'FGM', 'FGM'),
 (gen_random_uuid(), 'Pathfinder – for Private Law Proceedings', 'Pathfinder – for Private Law Proceedings'),
 (gen_random_uuid(), 'Domestic Abuse Protection Order (DAPOs)', 'Domestic Abuse Protection Order (DAPOs)'),
 (gen_random_uuid(), 'Benefits', 'Benefits');

-- Bulk seed service from search_service
INSERT INTO service_area (id, name, name_cy, description, description_cy, online_url, online_text, online_text_cy, text,
                    text_cy, catchment_method, type, sort_order, area_of_law_id)
VALUES (gen_random_uuid(), 'Money claims', 'Hawliadau am arian',
  'Claims for when you are owed money or responding to money claims against you.',
  'Hawliadau pan mae arian yn ddyledus ichi neu ymateb i hawliadau am arian yn eich erbyn.',
  'https://www.gov.uk/make-money-claim', 'Make a money claim online', 'Gwneud hawliad am arian ar-lein',
  'We manage your money claims applications at our central service centre. Find where to send your documents or ask about your application’s progress.',
  'Rydym yn rheoli eich ceisiadau am hawliadau am arian yn ein canolfan wasanaeth ganolog', 'postcode', 'civil',
  '1', NULL),
 (gen_random_uuid(), 'Tax', 'Treth', 'Appealing a tax decision.', 'Apelio yn erbyn penderfyniad treth.', NULL,
  NULL, NULL, NULL, NULL, 'proximity', 'other', '7',
  NULL),
 (gen_random_uuid(), 'Benefits', 'Budd-daliadau',
  'Appealing entitlement to benefits such as Personal Independence Payment (PIP), Employment and Support Allowance (ESA) or Universal Credit.',
  'Apelio yn erbyn hawl i gael budd-daliadau fel Taliad Annibyniaeth Personol (PIP), Lwfans Cyflogaeth a Chymorth (ESA) neu Gredyd Cynhwysol',
  'https://www.gov.uk/appeal-benefit-decision/submit-appeal', 'Appeal a benefits decision online',
  'Apelio yn erbyn penderfyniad budd-daliadau ar-lein',
  'We manage benefits appeals at our central service centre. Find where to send your documents or ask about your application’s progress.',
  'Rydym yn rheoli apeliadau budd-daliadau yn ein canolfan wasanaeth ganolog', 'proximity', 'other', '5',
  NULL),
 (gen_random_uuid(), 'Civil partnership', 'Partneriaeth sifil', 'Ending a civil partnership.',
  'Dod â phartneriaeth sifil i ben.', NULL, NULL, NULL,
  'We manage applications to dissolve a civil partnership at our central service centre. Find where to send your documents or ask about your application’s progress.',
  'Rydym yn rheoli ceisiadau i ddiddymu partneriaeth sifil yn ein canolfan wasanaeth ganolog', 'local-authority',
  'family', '10', NULL),
 (gen_random_uuid(), 'Probate', 'Profiant',
  'Applying for probate, storing a will, settlement and disputes over a deceased person''''s property, money and possessions.',
  'Gwneud cais am brofiant, storio ewyllys, setliad ac anghydfod ynghylch eiddo, arian a meddiannau unigolyn ymadawedig.',
  'https://www.gov.uk/applying-for-probate/apply-for-probate', 'Apply for probate online',
  'Gwneud cais am brofiant ar-lein',
  'We manage your probate applications at our central service centre. Find where to send your documents or ask about your application''s progress.',
  'Rydym yn rheoli eich ceisiadau profiant yn ein canolfan wasanaeth ganolog', 'proximity', 'family', '2',
  NULL),
 (gen_random_uuid(), 'Single Justice Procedure', 'Mân droseddau',
  'T.V. Licensing and minor traffic offences such as speeding',
  'Y Weithdrefn Un Ynad, Dirwyon trwydded deledu, dirwyon goryrru neu barcio.', NULL, NULL, NULL,
  'We manage minor criminal offences at our central service centre. Find where to send your documents or ask about your case.',
  'Rydym yn rheoli mân droseddau yn ein canolfan wasanaeth ganolog', 'proximity', 'other', '8',
  NULL),
 (gen_random_uuid(), 'Childcare arrangements if you separate from your partner',
  'Trefniadau gofal plant os ydych yn gwahanu oddi wrth eich partner.',
  'Making child arrangements if you divorce or separate.',
  'Gwneud trefniadau plant os ydych yn ysgaru neu’n gwahanu.',
  'https://apply-to-court-about-child-arrangements.service.justice.gov.uk/', NULL, NULL, NULL, NULL,
  'local-authority', 'family', '19', NULL),
 (gen_random_uuid(), 'Claims against employers', 'Honiadau yn erbyn cyflogwyr',
  'Appealing a decision about employment disputes related to pay, unfair dismissal and discrimination.',
  'Apelio yn erbyn penderfyniad am anghydfod cyflogaeth sy''''n ymwneud â thâl, diswyddo annheg a gwahaniaethu.',
  NULL, NULL, NULL, NULL, NULL, 'proximity', 'other', '6',
  NULL),
 (gen_random_uuid(), 'High Court district registry', 'cofrestrfa dosbarth yr Uchel Lys',
  'Courts that deal with the most serious and high profile cases in criminal and civil law.',
  'Llysoedd sy''n delio â''r achosion mwyaf difrifol a phroffil uchel mewn cyfraith droseddol a chyfraith sifil.',
  NULL, NULL, NULL, NULL, NULL, 'proximity', 'other', '19',
  NULL),
 (gen_random_uuid(), 'Female Genital Mutilation Protection Orders',
  'Gorchymyn Amddiffyn rhag Anffurfio Organau Cenhedlu Benywod',
  'Support for legal protection for victims of female genital mutilation.',
  'Cymorth i ddiogelu''n gyfreithiol dioddefwyr anffurfio organau cenhedlu benywod.', NULL, NULL, NULL, NULL,
  NULL, 'proximity', 'family', '19', NULL),
 (gen_random_uuid(), 'Divorce', 'Ysgariad',
  'Ending a marriage, getting a legal separation or help with money, property and children during a divorce.',
  'Dod â phriodas i ben, gwahanu’n gyfreithiol neu gael help gydag arian, eiddo a phlant yn ystod ysgariad.',
  'https://www.gov.uk/apply-for-divorce', 'Apply for a divorce online', 'Gwneud cais am ysgariad ar-lein', NULL,
  NULL, 'local-authority', 'family', '9',
  NULL),
 (gen_random_uuid(), 'Bankruptcy', 'Methdaliad',
  'Opposing a bankruptcy petition, support for a person at risk of violence order, cancelling a bankruptcy.',
  'Gwrthwynebu deiseb methdaliad, gorchymyn i gefnogi unigolyn sydd mewn perygl o drais, canslo methdaliad',
  'https://www.gov.uk/apply-for-bankruptcy', NULL, NULL, NULL, NULL, 'postcode', 'civil', '4',
  NULL),
 (gen_random_uuid(), 'Housing', 'Tai', 'Tenant evictions and rent or mortgage disputes.',
  'Dadfeddiannu tenantiaid ac anghydfod rhent neu forgais.',
  'https://www.gov.uk/possession-claim-online-recover-property', 'Make or respond to a possession claim online',
  'Gwneud neu ymateb i hawliad meddiant ar-lein', NULL, NULL, 'postcode', 'civil', '3',
  NULL),
 (gen_random_uuid(), 'Domestic abuse', 'Cam-drin domestig',
  'Support for an injunction if you''ve been the victim of domestic abuse.',
  'Cymorth ar gyfer gwaharddeb os ydych wedi dioddef cam-drin domestig.', NULL, NULL, NULL, NULL, NULL,
  'proximity', 'family', '19', NULL),
 (gen_random_uuid(), 'Other criminal offences', 'Troseddau mawr',
  'Criminal cases at a Crown or Magistrates'' Court',
  'Achosion troseddol mawr yn Llys y Goron neu mewn Llys Ynadon.', NULL, NULL, NULL,
  'We manage major criminal offences at our central service centre. Find where to send your documents or ask about your case.',
  'Rydym yn rheoli troseddau mawr yn ein canolfan wasanaeth ganolog', 'proximity', 'other', '19',
  NULL),
 (gen_random_uuid(), 'Forced marriage', 'Priodas dan orfod', 'Being made to marry against your will.',
  'Cael eich gorfodi i briodi yn erbyn eich ewyllys.', NULL, NULL, NULL, NULL, NULL, 'proximity', 'family', '19',
  NULL),
 (gen_random_uuid(), 'Immigration and asylum', 'Mewnfudo',
  'Seeking asylum, right to live in the UK, and appealing deportation.',
  'Ceisio lloches, hawl i fyw yn y DU, ac apelio yn erbyn allgludiad.', NULL, NULL, NULL, NULL, NULL, 'proximity',
  'other', '19', NULL),
 (gen_random_uuid(), 'Adoption', 'Mabwysiadu', 'Support for a child adoption application.',
  'Cymorth ar gyfer cais i fabwysiadu plentyn.', NULL, NULL, NULL, NULL, NULL, 'local-authority', 'family', '19',
  NULL),
 (gen_random_uuid(), 'Financial remedy', 'Rhwymedi Ariannol',
  'Making an application to settle your finances following a divorce.',
  'Gwneud cais i setlo materion ariannol yn dilyn ysgariad neu ddiweddu partneriaeth sifil.',
  'https://www.gov.uk/money-property-when-relationship-ends', NULL, NULL, NULL, NULL, NULL, 'family', '11',
  NULL);

-- Bulk seed court_types from search_courttype
INSERT INTO court_types (id, name)
VALUES (gen_random_uuid(), 'Magistrates'' Court'),
 (gen_random_uuid(), 'Family Court'),
 (gen_random_uuid(), 'Tribunal'),
 (gen_random_uuid(), 'County Court'),
 (gen_random_uuid(), 'Crown Court');

-- Seed `service` from search_service
INSERT INTO service (id, name, name_cy, description, description_cy)
VALUES (gen_random_uuid(), 'Money', 'Arian',
  'Money claims, rent or mortgage disputes, bankruptcy, job disputes related to pay, appealing a tax or benefits decision.',
  'Hawliadau am arian, anghydfod rhent neu forgais, methdaliad, anghydfod yn gysylltiedig â swyddi a thâl, apelio yn erbyn penderfyniad treth neu fudd-daliadau.'),
 (gen_random_uuid(), 'Probate, divorce or ending civil partnerships',
  'Profiant, ysgariad neu derfynu partneriaethau sifil',
  'Probate application and disputes, divorce, ending a civil partnership.',
  'Ceisiadau am brofiant ac anghydfod yn gysylltiedig â phrofiant, ysgariad, dod â phartneriaeth sifil i ben.'),
 (gen_random_uuid(), 'Childcare and parenting', 'Gofal plant a rhianta',
  'Arrangements for looking after your children if you separate from your partner or making an adoption legal.',
  'Trefniadau ar gyfer gofalu am eich plant os ydych yn gwahanu oddi wrth eich partner neu''n mabwysiadu''n gyfreithlon.'),
 (gen_random_uuid(), 'Harm and abuse', 'Niwed a cham-drin',
  'Applying for an injunction against someone who is harassing or abusing you, being made to marry against your will or preventing Female Genital Mutilation (FGM).',
  'Gwneud cais am waharddeb yn erbyn rhywun sy''''n aflonyddu arnoch neu''''n eich cam-drin, cael eich gorfodi i briodi yn erbyn eich ewyllys neu atal Anffurfio Organau Cenhedlu Benywod (FGM).'),
 (gen_random_uuid(), 'Immigration and asylum', 'Mewnfudo a lloches',
  'Seeking asylum, right to live in the UK, and appealing deportation.',
  'Ceisio lloches, hawl i fyw yn y DU, ac apelio yn erbyn allgludiad.'),
 (gen_random_uuid(), 'Crime', 'Troseddu',
  'Single Justice Procedure and other criminal cases at a Crown or Magistrates’ Court',
  'Y Weithdrefn Un Ynad ac achosion troseddol eraill yn Llys y Goron neu''r Llys Ynadon.'),
 (gen_random_uuid(), 'High Court district registries', 'Cofrestrfeydd dosbarth yr Uchel Lys',
  'Courts that deal with the most serious and high profile cases in criminal and civil law.',
  'Llysoedd sy''n delio â''r achosion mwyaf difrifol a phroffil uchel mewn cyfraith droseddol a chyfraith sifil.');
