UPDATE contact_description_types cdt
SET name_cy = v.name_cy
FROM (
    VALUES
        ('Accessibility enquiries', 'Ymholiadau hygyrchedd'),
        ('Administration', 'Gweinyddiaeth'),
        ('Administrative Court appointments', 'Llys Gweinyddol - apwyntiadau'),
        ('Administrative Court enquiries', 'Llys Gweinyddol - ymholiadau'),
        ('Administrative Court lists', 'Llys Gweinyddol - rhestrau'),
        ('Admiralty Court appointments', 'Llys y Morlys - apwyntiadau'),
        ('Admiralty Court enquiries', 'Llys y Morlys - ymholiadau'),
        ('Admiralty Court lists', 'Llys y Morlys - rhestrau'),
        ('Adoption', 'Mabwysiadu'),
        ('Appointments', 'Apwyntiadau'),
        ('Asylum Support Tribunal enquiries', 'Tribiwnlys Cefnogi Ceiswyr Lloches - ymholiadau'),
        ('Bail applications', 'Ceisiadau am fechnïaeth'),
        ('Bailiff enquiries', 'Ymholiadau beilïaid'),
        ('Building facilities', 'Cyfleusterau yn yr adeilad'),
        ('Business and Property Court appointments', 'Y Llys Busnes ac Eiddo - apwyntiadau'),
        ('Business and Property Court enquiries', 'Y Llys Busnes ac Eiddo - ymholiadau'),
        ('Business and Property Court lists', 'Y Llys Busnes ac Eiddo - rhestrau'),
        ('Case progression', 'Cyflymu Achosion'),
        ('Central London county court enquiries', 'Llys Sirol Canol Llundain - ymholiadau'),
        ('Centralised Attachment of Earnings (CAPS)', 'System Ganolog Taliadau Atafaelu Enillion (CAPS)'),
        ('Chancery division appointments', 'Yr Adran Siawnsri - apwyntiadau'),
        ('Chancery division court lists', 'Yr Adran Siawnsri - rhestrau llys'),
        ('Chancery division enquiries', 'Yr Adran Siawnsri - ymholiadau'),
        ('Chancery division issues', 'Yr Adran Siawnsri - materion'),
        ('Chancery Masters appointments', 'Meistri''r Siawnsri - apwyntiadau'),
        ('Child arrangements', 'Trefniadau plant'),
        ('Child maintenance', 'Cynhaliaeth plant'),
        ('Children in care', 'Plant mewn gofal'),
        ('Circuit Commercial Court appointments', 'Cylchdaith y Llys Masnach - apwyntiadau'),
        ('Circuit Commercial Court enquiries', 'Cylchdaith y Llys Masnach - ymholiadau'),
        ('Circuit Commercial Court lists', 'Cylchdaith y Llys Masnach - rhestrau'),
        ('Circuit Court appointments', 'Llys Cylchdaith - apwyntiadau'),
        ('Circuit Court enquiries', 'Llys Cylchdaith - ymholiadau'),
        ('Circuit Court lists', 'Llys Cylchdaith - rhestrau'),
        ('Citizens Advice Witness Service', 'Gwasanaeth Tystion Cyngor Ar Bopeth'),
        ('Civil appointments', 'Llys Sifil - apwyntiadau'),
        ('Civil court lists', 'Llys Sifil - rhestrau'),
        ('Civil enquiries', 'Llys Sifil - ymholiadau'),
        ('Commercial Court appointments', 'Y Llys Masnach - apwyntiadau'),
        ('Commercial Court enquiries', 'Y Llys Masnach - ymholiadau'),
        ('Commercial Court lists', 'Y Llys Masnach - rhestrau'),
        ('Companies winding up', 'Dirwyn Cwmnïau i Ben'),
        ('Confiscation enquiries', 'Ymholiadau atafaelu'),
        ('County court appointments', 'Llys Sirol - apwyntiadau'),
        ('County court enquiries', 'Llys Sirol - ymholiadau'),
        ('County court lists', 'Llys Sirol - rhestrau'),
        ('Court clerks', 'Clercod y llys'),
        ('Court lists', 'Rhestrau''r Llys'),
        ('Court of Appeal Civil Division', 'Llys Apêl - Adran Sifil'),
        ('Court of Appeal Criminal Division', 'Llys Apêl - Adran Droseddol'),
        ('Court of Protection', 'Y Llys Gwarchod'),
        ('Criminal Injuries Compensation Tribunal enquiries', 'Tribiwnlys Iawndal am Anafiadau Troseddol - ymholiadau'),
        ('Crown Court appointments', 'Llys y Goron - apwyntiadau'),
        ('Crown Court lists', 'Llys y Goron - rhestrau'),
        ('Debt respite scheme enquiries', 'Cynllun seibiant o ddyledion - ymholiadau'),
        ('District court appointments', 'Llys Dosbarth - apwyntiadau'),
        ('District court enquiries', 'Llys Dosbarth - ymholiadau'),
        ('District court lists', 'Llys Dosbarth - rhestrau'),
        ('Divorce enquiries', 'Ymholiadau am ysgaru'),
        ('Domestic violence remedy orders', 'Gorchmynion rhwymedi cam-drin domestig'),
        ('Employment Tribunal enquiries', 'Tribiwnlys Cyflogaeth - ymholiadau'),
        ('Enforcement enquiries', 'Gorfodi - ymholiadau'),
        ('Enforcement fine enquiries', 'Gorfodi dirwyon - ymholiadau'),
        ('Family court appointments', 'Llys Teulu - apwyntiadau'),
        ('Family court lists', 'Llys teulu - rhestrau'),
        ('Family private law', 'Cyfraith breifat - teulu'),
        ('Family public law', 'Cyfraith gyhoeddus - teulu'),
        ('Fee enquiries', 'Ymholiadau am ffioedd'),
        ('Female genital mutilation protection orders', 'Gorchmynion Amddiffyn rhag Anffurfio Organau Cenhedlu Benywod (FGM)'),
        ('Finances', 'Cyllid'),
        ('Financial remedy during divorce', 'Rhwymedi ariannol yn ystod ysgariad'),
        ('Fine enquiries', 'Ymholiadau dirwyon'),
        ('Fixed penalties', 'Cosbau penodedig'),
        ('Forced marriage protection orders', 'Gorchmynion Amddiffyn rhag Priodas dan Orfod'),
        ('High Court appeals', 'Yr Uchel Lys - apeliadau'),
        ('High Court appointments', 'Yr Uchel Lys - apwyntiadau'),
        ('High Court enquiries', 'Yr Uchel Lys - ymholiadau'),
        ('High Court lists', 'Yr Uchel Lys - rhestrau'),
        ('Immigration and Asylum appeals enquiries', 'Apeliadau Mewnfudo a Lloches - ymholiadau'),
        ('Immigration and Asylum Tribunal appointments', 'Tribiwnlys Mewnfudo a Lloches - apwyntiadau'),
        ('Immigration and Asylum Tribunal court lists', 'Tribiwnlys Mewnfudo a Lloches - rhestrau'),
        ('Enquiries', 'Ymholiadau'),
        ('Immigration and Asylum Tribunal enquiries', 'Tribiwnlys Mewnfudo a Lloches - ymholiadau'),
        ('Insolvency and Companies Court appointments', 'Llys Ansolfedd a Chwmnïau - apwyntiadau'),
        ('Insolvency and Companies Court enquiries', 'Llys Ansolfedd a Chwmnïau - ymholiadau'),
        ('Insolvency and Companies Court issues', 'Llys Ansolfedd a Chwmnïau - materion'),
        ('Insolvency and Companies Court lists', 'Llys Ansolfedd a Chwmnïau - rhestrau'),
        ('Issues', 'Materion'),
        ('King''s Bench Division appointments', 'Adran Mainc y Brenin - apwyntiadau'),
        ('King''s Bench Division court lists', 'Adran Mainc y Brenin - rhestrau'),
        ('King''s Bench Division enquiries', 'Adran Mainc y Brenin - ymholiadau'),
        ('Legal aid', 'Cymorth cyfreithiol'),
        ('London Circuit Commercial Court appointments', 'Y Llys Masnach - Cylchdaith Llundain -  apwyntiadau'),
        ('London Circuit Commercial Court enquiries', 'Y Llys Masnach - Cylchdaith Llundain -   ymholiadau'),
        ('London Circuit Commercial Court lists', 'Y Llys Masnach - Cylchdaith Llundain -   rhestrau'),
        ('Magistrates'' court appointments', 'Llys Ynadon - apwyntiadau'),
        ('Magistrates'' court enquiries', 'Llys Ynadon - ymholiadau'),
        ('Magistrates'' court lists', 'Llys Ynadon - rhestrau'),
        ('Mediation appointments', 'Apwyntiadau cyfryngu'),
        ('Mediation enquiries', 'Ymholiadau cyfryngu'),
        ('Online civil money claims enquiries', 'Hawliadau am arian sifil ar-lein (OCMC)'),
        ('Orders and accounts', 'Gorchmynion a chyfrifon'),
        ('Pay a fine', 'Talu dirwy'),
        ('Payments', 'Taliadau'),
        ('Planning Court', 'Y Llys Cynllunio'),
        ('Possession', 'Meddiannu'),
        ('Post court enquiries', 'Ymholiadau ar ôl llys'),
        ('Pre and post court enquiries', 'Ymholiadau cyn ac ar ôl llys'),
        ('Pre court enquiries', 'Ymholiadau cyn llys'),
        ('Probate enquiries', 'Ymholiadau profiant'),
        ('Registrar', 'Cofrestrydd'),
        ('Registry enquiries', 'Ymholiadau cofrestrfa'),
        ('Security', 'Diogelwch'),
        ('Senior courts costs office', 'Swyddfa costau''r uwch lysoedd'),
        ('Single Justice Procedures enquiries', 'Ymholiadau Gweithdrefn Un Ynad'),
        ('Social Security and Child Support benefit appeals enquiries', 'Ymholiadau apeliadau Nawdd Cymdeithasol a Chynnal Plant (SSCS)'),
        ('Social Security and Child Support Tribunal enquiries', 'Ymholiadau''r Tribiwnlys Nawdd Cymdeithasol a Chynnal Plant (SSCS)'),
        ('Support Through Court', 'Support Through Court (STC)'),
        ('Switchboard', 'Switsfwrdd'),
        ('Technology and Construction Court appointments', 'Llys Technoleg ac Adeiladwaith - apwyntiadaui'),
        ('Technology and Construction Court enquiries', 'Llys Technoleg ac Adeiladwaith - ymholiadau'),
        ('Technology and Construction Court issues', 'Llys Technoleg ac Adeiladwaith - materion'),
        ('Technology and Construction Court lists', 'Llys Technoleg ac Adeiladwaith - rhestrau'),
        ('Textphone', 'Ffôn Testun'),
        ('Welsh language helpline', 'Llinell Gymorth Gymraeg'),
        ('Crown Court enquiries', 'Ymholiadau Llys y Goron'),
        ('Family court enquiries', 'Ymholiadau Llys Teulu'),
        ('Jury service', 'Gwasanaeth rheithgor'),
        ('Pay a fee', 'Talu ffi'),
        ('Transcripts', 'Trawsgrifiadau'),
        ('Acknowledgement of service','Cydnabyddiad Cyflwyno'),
        ('Application enquiries','Ymholiadau am gais'),
        ('Attachment of earnings applications','Ceisiadau am Orchymyn Atafaelu Enillion'),
        ('Charging orders','Gorchmynion arwystlo'),
        ('Claim responses','Ymatebion i hawliad'),
        ('Directions questionnaires','Holiaduron Cyfarwyddiadau'),
        ('Help with fees','Help i dalu ffioedd'),
        ('Ongoing attachment of earnings order issues','Problemau parhaus gyda gorchymyn atafaelu enillion'),
        ('Request a certificate of satisfaction','Gwneud cais am dystysgrif bodlonrwydd'),
        ('Request for judgment','Cais am ddyfarniad'),
        ('Scottish enquiries','Ymholiadau yn Yr Alban'),
        ('Traffic enforcement centre enquiries','Ymholiadau Canolfan Gorfodi Traffig'),
        ('Warrants and writs of control','Gwarantau neu writ rheolaeth')
) AS v(name, name_cy)
WHERE cdt.name = v.name;

ALTER TABLE court_types
  ADD COLUMN IF NOT EXISTS name_cy VARCHAR;

UPDATE court_types ct
SET name_cy = v.name_cy
  FROM (
    VALUES
        ('Magistrates'' Court', 'Llys Ynadon'),
        ('Family Court', 'Llys Teulu'),
        ('Tribunal', 'Tribiwnlys'),
        ('County Court', 'Llys Sirol'),
        ('Crown Court', 'Llys y Goron')
) AS v(name, name_cy)
WHERE ct.name = v.name;

UPDATE area_of_law_types aolt
SET name_cy = v.name_cy
  FROM (
    VALUES
        ('Divorce', 'Ysgariad'),
        ('Civil partnership', 'Partneriaeth sifil'),
        ('High Court District Registry', 'Cofrestrfa Ddosbarth yr Uchel Lys'),
        ('Adoption', 'Mabwysiadu'),
        ('Social security', 'Nawdd Cymdeithasol'),
        ('Housing possession', 'Meddiannu eiddo'),
        ('Money claims', 'Hawliadau am arian'),
        ('Employment', 'Cyflogaeth'),
        ('Tax', 'Treth'),
        ('Children', 'Plant'),
        ('Domestic violence', 'Trais domestig'),
        ('Crime', 'Trosedd'),
        ('Civil', 'Sifil'),
        ('Single justice procedure', 'Y Weithdrefn Un Ynad'),
        ('High Court', 'Yr Uchel Lys'),
        ('Court Of Appeal', 'Y Llys Apêl'),
        ('Financial Remedy', 'Rhwymedi Ariannol'),
        ('Business and Property', 'Busnes ac Eiddo'),
        ('Bankruptcy', 'Methdaliad'),
        ('Immigration', 'Mewnfudo'),
        ('Probate', 'Profiant'),
        ('Forced marriage', 'Priodas dan orfod'),
        ('FGM', 'Anffurfio Organau Cenhedlu Benywod (FGM)'),
        ('Pathfinder – for Private Law Proceedings', 'Cynllun Braenaru – ar gyfer Achosion Cyfraith Breifat'),
        ('Domestic Abuse Protection Order (DAPOs)', 'Gorchymyn Diogelu Rhag Cam-drin Domestig (DAPOs)'),
        ('Benefits', 'Budd-daliadau')
) AS v(name, name_cy)
WHERE aolt.name = v.name;

ALTER TABLE court_dxcodes
  ADD COLUMN IF NOT EXISTS explanation_cy VARCHAR(250);

ALTER TABLE court_fax
  ADD COLUMN IF NOT EXISTS description_cy VARCHAR(250);


