-- Add Scotland local authority custodian-code mappings.
-- These rows support lookups in OsService for Scottish postcodes.
INSERT INTO local_authority_types (id, name, custodian_code, child_custodian_codes) VALUES
  (gen_random_uuid(), 'Aberdeen City Council', 9051, DEFAULT),
  (gen_random_uuid(), 'Aberdeenshire Council', 9052, DEFAULT),
  (gen_random_uuid(), 'Angus Council', 9053, DEFAULT),
  (gen_random_uuid(), 'Argyll and Bute Council', 9054, DEFAULT),
  (gen_random_uuid(), 'City of Edinburgh Council', 9064, DEFAULT),
  (gen_random_uuid(), 'Clackmannanshire Council', 9056, DEFAULT),
  (gen_random_uuid(), 'Comhairle nan Eilean Siar', 9020, DEFAULT),
  (gen_random_uuid(), 'Dumfries and Galloway Council', 9058, DEFAULT),
  (gen_random_uuid(), 'Dundee City Council', 9059, DEFAULT),
  (gen_random_uuid(), 'East Ayrshire Council', 9060, DEFAULT),
  (gen_random_uuid(), 'East Dunbartonshire Council', 9061, DEFAULT),
  (gen_random_uuid(), 'East Lothian Council', 9062, DEFAULT),
  (gen_random_uuid(), 'East Renfrewshire Council', 9063, DEFAULT),
  (gen_random_uuid(), 'Falkirk Council', 9065, DEFAULT),
  (gen_random_uuid(), 'Fife Council', 9066, DEFAULT),
  (gen_random_uuid(), 'Glasgow City Council', 9067, DEFAULT),
  (gen_random_uuid(), 'Inverclyde Council', 9069, DEFAULT),
  (gen_random_uuid(), 'Midlothian Council', 9070, DEFAULT),
  (gen_random_uuid(), 'North Ayrshire Council', 9072, DEFAULT),
  (gen_random_uuid(), 'North Lanarkshire Council', 9073, DEFAULT),
  (gen_random_uuid(), 'Orkney Islands Council', 9000, DEFAULT),
  (gen_random_uuid(), 'Perth and Kinross Council', 9074, DEFAULT),
  (gen_random_uuid(), 'Renfrewshire Council', 9075, DEFAULT),
  (gen_random_uuid(), 'Scottish Borders Council', 9055, DEFAULT),
  (gen_random_uuid(), 'Shetland Islands Council', 9010, DEFAULT),
  (gen_random_uuid(), 'South Ayrshire Council', 9076, DEFAULT),
  (gen_random_uuid(), 'South Lanarkshire Council', 9077, DEFAULT),
  (gen_random_uuid(), 'Stirling Council', 9078, DEFAULT),
  (gen_random_uuid(), 'The Highland Council', 9068, DEFAULT),
  (gen_random_uuid(), 'The Moray Council', 9071, DEFAULT),
  (gen_random_uuid(), 'West Dunbartonshire Council', 9057, DEFAULT),
  (gen_random_uuid(), 'West Lothian Council', 9079, DEFAULT);
