-- Refresh the table and add local authorities. Most current as of Nov 2025
-- Only for England and Wales
DELETE FROM local_authority_types;

-- Alter the table so that we add the two new columns. Just to make it so that we
-- have it all in one go, both for dropdown and for the lookup too.
ALTER TABLE local_authority_types
  ADD COLUMN custodian_code        INT,
  ADD COLUMN child_custodian_codes INT[] NOT NULL DEFAULT '{}'::int[];

-- Create a new table to establish the child/parent relationship district wise
-- Note: Ordnance Survey does not provide the council name, only the LOCAL_CUSTODIAN_CODE
INSERT INTO local_authority_types (id, name, custodian_code, child_custodian_codes) VALUES
  (gen_random_uuid(), 'Adur District Council', 3805, DEFAULT),
  (gen_random_uuid(), 'Amber Valley Borough Council', 1005, DEFAULT),
  (gen_random_uuid(), 'Arun District Council', 3810, DEFAULT),
  (gen_random_uuid(), 'Ashfield District Council', 3005, DEFAULT),
  (gen_random_uuid(), 'Ashford Borough Council', 2205, DEFAULT),
  (gen_random_uuid(), 'Babergh District Council', 3505, DEFAULT),
  (gen_random_uuid(), 'Barnsley Metropolitan Borough Council', 4405, DEFAULT),
  (gen_random_uuid(), 'Basildon Borough Council', 1505, DEFAULT),
  (gen_random_uuid(), 'Basingstoke and Deane Borough Council', 1705, DEFAULT),
  (gen_random_uuid(), 'Bassetlaw District Council', 3010, DEFAULT),
  (gen_random_uuid(), 'Bath and North East Somerset Council', 114, DEFAULT),
  (gen_random_uuid(), 'Bedford Borough Council', 235, DEFAULT),
  (gen_random_uuid(), 'Birmingham City Council', 4605, DEFAULT),
  (gen_random_uuid(), 'Blaby District Council', 2405, DEFAULT),
  (gen_random_uuid(), 'Blackburn with Darwen Borough Council', 2372, DEFAULT),
  (gen_random_uuid(), 'Blackpool Borough Council', 2373, DEFAULT),
  (gen_random_uuid(), 'Blaenau Gwent County Borough Council', 6910, DEFAULT),
  (gen_random_uuid(), 'Bolsover District Council', 1010, DEFAULT),
  (gen_random_uuid(), 'Bolton Metropolitan Borough Council', 4205, DEFAULT),
  (gen_random_uuid(), 'Borough Council of Kings Lynn and West Norfolk', 2635, DEFAULT),
  (gen_random_uuid(), 'Borough of Broxbourne', 1905, DEFAULT),
  (gen_random_uuid(), 'Boston Borough Council', 2505, DEFAULT),
  (gen_random_uuid(), 'Bournemouth, Christchurch and Poole Council', 1260, DEFAULT),
  (gen_random_uuid(), 'Bracknell Forest Council', 335, DEFAULT),
  (gen_random_uuid(), 'Braintree District Council', 1510, DEFAULT),
  (gen_random_uuid(), 'Breckland Council', 2605, DEFAULT),
  (gen_random_uuid(), 'Brentwood Borough Council', 1515, DEFAULT),
  (gen_random_uuid(), 'Bridgend County Borough Council', 6915, DEFAULT),
  (gen_random_uuid(), 'Brighton and Hove City Council', 1445, DEFAULT),
  (gen_random_uuid(), 'Bristol City Council', 116, DEFAULT),
  (gen_random_uuid(), 'Broadland District Council', 2610, DEFAULT),
  (gen_random_uuid(), 'Bromsgrove District Council', 1805, DEFAULT),
  (gen_random_uuid(), 'Broxtowe Borough Council', 3015, DEFAULT),
  (gen_random_uuid(), 'Buckinghamshire Council', 440, DEFAULT),
  (gen_random_uuid(), 'Burnley Borough Council', 2315, DEFAULT),
  (gen_random_uuid(), 'Bury Metropolitan Borough Council', 4210, DEFAULT),
  (gen_random_uuid(), 'Caerphilly County Borough Council', 6920, DEFAULT),
  (gen_random_uuid(), 'Calderdale Metropolitan Borough Council', 4710, DEFAULT),
  (gen_random_uuid(), 'Cambridge City Council', 505, DEFAULT),
  (gen_random_uuid(), 'Cambridgeshire County Council', 535, ARRAY[505,510,515,520,530]),
  (gen_random_uuid(), 'Cannock Chase District Council', 3405, DEFAULT),
  (gen_random_uuid(), 'Canterbury City Council', 2210, DEFAULT),
  (gen_random_uuid(), 'Carmarthenshire County Council', 6825, DEFAULT),
  (gen_random_uuid(), 'Castle Point Borough Council', 1520, DEFAULT),
  (gen_random_uuid(), 'Central Bedfordshire Council', 240, DEFAULT),
  (gen_random_uuid(), 'Ceredigion County Council', 6820, DEFAULT),
  (gen_random_uuid(), 'Charnwood Borough Council', 2410, DEFAULT),
  (gen_random_uuid(), 'Chelmsford City Council', 1525, DEFAULT),
  (gen_random_uuid(), 'Cheltenham Borough Council', 1605, DEFAULT),
  (gen_random_uuid(), 'Cherwell District Council', 3105, DEFAULT),
  (gen_random_uuid(), 'Cheshire East Council', 660, DEFAULT),
  (gen_random_uuid(), 'Cheshire West and Chester Council', 665, DEFAULT),
  (gen_random_uuid(), 'Chesterfield Borough Council', 1015, DEFAULT),
  (gen_random_uuid(), 'Chichester District Council', 3815, DEFAULT),
  (gen_random_uuid(), 'Chorley Council', 2320, DEFAULT),
  (gen_random_uuid(), 'City and County of Swansea Council', 6855, DEFAULT),
  (gen_random_uuid(), 'City of Bradford Metropolitan District Council', 4705, DEFAULT),
  (gen_random_uuid(), 'City of Cardiff Council', 6815, DEFAULT),
  (gen_random_uuid(), 'City of Lincoln Council', 2515, DEFAULT),
  (gen_random_uuid(), 'City of London Corporation', 5030, DEFAULT),
  (gen_random_uuid(), 'City of Westminster', 5990, DEFAULT),
  (gen_random_uuid(), 'City of Wolverhampton Council', 4635, DEFAULT),
  (gen_random_uuid(), 'City of York Council', 2741, DEFAULT),
  (gen_random_uuid(), 'Colchester City Council', 1530, DEFAULT),
  (gen_random_uuid(), 'Conwy County Borough Council', 6905, DEFAULT),
  (gen_random_uuid(), 'Cornwall Council', 840, DEFAULT),
  (gen_random_uuid(), 'Cotswold District Council', 1610, DEFAULT),
  (gen_random_uuid(), 'Council of the Isles of Scilly', 835, DEFAULT),
  (gen_random_uuid(), 'Coventry City Council', 4610, DEFAULT),
  (gen_random_uuid(), 'Crawley Borough Council', 3820, DEFAULT),
  (gen_random_uuid(), 'Cumberland Council', 940, DEFAULT),
  (gen_random_uuid(), 'Dacorum Borough Council', 1910, DEFAULT),
  (gen_random_uuid(), 'Darlington Borough Council', 1350, DEFAULT),
  (gen_random_uuid(), 'Dartford Borough Council', 2215, DEFAULT),
  (gen_random_uuid(), 'Denbighshire County Council', 6830, DEFAULT),
  (gen_random_uuid(), 'Derby City', 1055, DEFAULT),
  (gen_random_uuid(), 'Derbyshire County Council', 1050, ARRAY[1005,1010,1015,1045,1025,1030,1035,1040]),
  (gen_random_uuid(), 'Derbyshire Dales District Council', 1045, DEFAULT),
  (gen_random_uuid(), 'Devon County Council', 1155, ARRAY[1105,1110,1135,1115,1125,1130,1145,1150]),
  (gen_random_uuid(), 'Doncaster Metropolitan Borough Council', 4410, DEFAULT),
  (gen_random_uuid(), 'Dorset Council', 1265, DEFAULT),
  (gen_random_uuid(), 'Dover District Council', 2220, DEFAULT),
  (gen_random_uuid(), 'Dudley Metropolitan Borough Council', 4615, DEFAULT),
  (gen_random_uuid(), 'Durham County Council', 1355, DEFAULT),
  (gen_random_uuid(), 'Eastbourne Borough Council', 1410, DEFAULT),
  (gen_random_uuid(), 'East Cambridgeshire District Council', 510, DEFAULT),
  (gen_random_uuid(), 'East Devon District Council', 1105, DEFAULT),
  (gen_random_uuid(), 'East Hampshire District Council', 1710, DEFAULT),
  (gen_random_uuid(), 'East Hertfordshire District Council', 1915, DEFAULT),
  (gen_random_uuid(), 'Eastleigh Borough Council', 1715, DEFAULT),
  (gen_random_uuid(), 'East Lindsey District Council', 2510, DEFAULT),
  (gen_random_uuid(), 'East Riding of Yorkshire Council', 2001, DEFAULT),
  (gen_random_uuid(), 'East Staffordshire Borough Council', 3410, DEFAULT),
  (gen_random_uuid(), 'East Suffolk District Council', 3540, DEFAULT),
  (gen_random_uuid(), 'East Sussex County Council', 1440, ARRAY[1410,1415,1425,1430,1435]),
  (gen_random_uuid(), 'Elmbridge Borough Council', 3605, DEFAULT),
  (gen_random_uuid(), 'Epping Forest District Council', 1535, DEFAULT),
  (gen_random_uuid(), 'Epsom and Ewell Borough Council', 3610, DEFAULT),
  (gen_random_uuid(), 'Erewash Borough Council', 1025, DEFAULT),
  (gen_random_uuid(), 'Essex County Council', 1585, ARRAY[1505,1510,1515,1520,1525,1530,1535,1540,1545,1550,1560,1570]),
  (gen_random_uuid(), 'Exeter City Council', 1110, DEFAULT),
  (gen_random_uuid(), 'Fareham Borough Council', 1720, DEFAULT),
  (gen_random_uuid(), 'Fenland District Council', 515, DEFAULT),
  (gen_random_uuid(), 'Flintshire County Council', 6835, DEFAULT),
  (gen_random_uuid(), 'Folkestone and Hythe District Council', 2250, DEFAULT),
  (gen_random_uuid(), 'Forest of Dean District Council', 1615, DEFAULT),
  (gen_random_uuid(), 'Fylde Borough Council', 2325, DEFAULT),
  (gen_random_uuid(), 'Gateshead Metropolitan Borough Council', 4505, DEFAULT),
  (gen_random_uuid(), 'Gedling Borough Council', 3020, DEFAULT),
  (gen_random_uuid(), 'Gloucester City Council', 1620, DEFAULT),
  (gen_random_uuid(), 'Gloucestershire County Council', 1600, ARRAY[1605,1610,1615,1620,1625,1630]),
  (gen_random_uuid(), 'Gosport Borough Council', 1725, DEFAULT),
  (gen_random_uuid(), 'Gravesham Borough Council', 2230, DEFAULT),
  (gen_random_uuid(), 'Great Yarmouth Borough Council', 2615, DEFAULT),
  (gen_random_uuid(), 'Guildford Borough Council', 3615, DEFAULT),
  (gen_random_uuid(), 'Gwynedd Council', 6810, DEFAULT),
  (gen_random_uuid(), 'Halton Borough Council', 650, DEFAULT),
  (gen_random_uuid(), 'Hampshire County Council', 1770, ARRAY[1705,1710,1715,1720,1725,1730,1735,1740,1750,1760,1765]),
  (gen_random_uuid(), 'Harborough District Council', 2415, DEFAULT),
  (gen_random_uuid(), 'Harlow Council', 1540, DEFAULT),
  (gen_random_uuid(), 'Hart District Council', 1730, DEFAULT),
  (gen_random_uuid(), 'Hartlepool Borough Council', 724, DEFAULT),
  (gen_random_uuid(), 'Hastings Borough Council', 1415, DEFAULT),
  (gen_random_uuid(), 'Havant Borough Council', 1735, DEFAULT),
  (gen_random_uuid(), 'Herefordshire Council', 1850, DEFAULT),
  (gen_random_uuid(), 'Hertfordshire County Council', 1900, ARRAY[1905,1910,1915,1920,1925,1930,1935,1940,1945,1950]),
  (gen_random_uuid(), 'Hertsmere Borough Council', 1920, DEFAULT),
  (gen_random_uuid(), 'High Peak Borough Council', 1030, DEFAULT),
  (gen_random_uuid(), 'Hinckley and Bosworth Borough Council', 2420, DEFAULT),
  (gen_random_uuid(), 'Horsham District Council', 3825, DEFAULT),
  (gen_random_uuid(), 'Hull City Council', 2004, DEFAULT),
  (gen_random_uuid(), 'Huntingdonshire District Council', 520, DEFAULT),
  (gen_random_uuid(), 'Hyndburn Borough Council', 2330, DEFAULT),
  (gen_random_uuid(), 'Ipswich Borough Council', 3515, DEFAULT),
  (gen_random_uuid(), 'Isle of Anglesey County Council', 6805, DEFAULT),
  (gen_random_uuid(), 'Isle of Wight Council', 2114, DEFAULT),
  (gen_random_uuid(), 'Kent County Council', 2275, ARRAY[2205,2210,2215,2220,2250,2230,2235,2245,2255,2260,2265,2270]),
  (gen_random_uuid(), 'Kirklees Council', 4715, DEFAULT),
  (gen_random_uuid(), 'Knowsley Metropolitan Borough Council', 4305, DEFAULT),
  (gen_random_uuid(), 'Lancashire County Council', 2371, ARRAY[2315,2320,2325,2330,2335,2340,2345,2350,2355,2360,2365,2370]),
  (gen_random_uuid(), 'Lancaster City Council', 2335, DEFAULT),
  (gen_random_uuid(), 'Leeds City Council', 4720, DEFAULT),
  (gen_random_uuid(), 'Leicester City Council', 2465, DEFAULT),
  (gen_random_uuid(), 'Leicestershire County Council', 2460, ARRAY[2405,2410,2415,2420,2430,2435,2440]),
  (gen_random_uuid(), 'Lewes District Council', 1425, DEFAULT),
  (gen_random_uuid(), 'Lichfield District Council', 3415, DEFAULT),
  (gen_random_uuid(), 'Lincolnshire County Council', 2500, ARRAY[2505,2515,2510,2520,2525,2530,2535]),
  (gen_random_uuid(), 'Liverpool City Council', 4310, DEFAULT),
  (gen_random_uuid(), 'London Borough of Barking and Dagenham', 5060, DEFAULT),
  (gen_random_uuid(), 'London Borough of Barnet', 5090, DEFAULT),
  (gen_random_uuid(), 'London Borough of Bexley', 5120, DEFAULT),
  (gen_random_uuid(), 'London Borough of Brent', 5150, DEFAULT),
  (gen_random_uuid(), 'London Borough of Bromley', 5180, DEFAULT),
  (gen_random_uuid(), 'London Borough of Camden', 5210, DEFAULT),
  (gen_random_uuid(), 'London Borough of Croydon', 5240, DEFAULT),
  (gen_random_uuid(), 'London Borough of Ealing', 5270, DEFAULT),
  (gen_random_uuid(), 'London Borough of Enfield', 5300, DEFAULT),
  (gen_random_uuid(), 'London Borough of Hackney', 5360, DEFAULT),
  (gen_random_uuid(), 'London Borough of Hammersmith & Fulham', 5390, DEFAULT),
  (gen_random_uuid(), 'London Borough of Haringey', 5420, DEFAULT),
  (gen_random_uuid(), 'London Borough of Harrow', 5450, DEFAULT),
  (gen_random_uuid(), 'London Borough of Havering', 5480, DEFAULT),
  (gen_random_uuid(), 'London Borough of Hillingdon', 5510, DEFAULT),
  (gen_random_uuid(), 'London Borough of Hounslow', 5540, DEFAULT),
  (gen_random_uuid(), 'London Borough of Islington', 5570, DEFAULT),
  (gen_random_uuid(), 'London Borough of Lambeth', 5660, DEFAULT),
  (gen_random_uuid(), 'London Borough of Lewisham', 5690, DEFAULT),
  (gen_random_uuid(), 'London Borough of Merton', 5720, DEFAULT),
  (gen_random_uuid(), 'London Borough of Newham', 5750, DEFAULT),
  (gen_random_uuid(), 'London Borough of Redbridge', 5780, DEFAULT),
  (gen_random_uuid(), 'London Borough of Richmond upon Thames', 5810, DEFAULT),
  (gen_random_uuid(), 'London Borough of Southwark', 5840, DEFAULT),
  (gen_random_uuid(), 'London Borough of Sutton', 5870, DEFAULT),
  (gen_random_uuid(), 'London Borough of Tower Hamlets', 5900, DEFAULT),
  (gen_random_uuid(), 'London Borough of Waltham Forest', 5930, DEFAULT),
  (gen_random_uuid(), 'London Borough of Wandsworth', 5960, DEFAULT),
  (gen_random_uuid(), 'Luton Borough Council', 230, DEFAULT),
  (gen_random_uuid(), 'Maidstone Borough Council', 2235, DEFAULT),
  (gen_random_uuid(), 'Maldon District Council', 1545, DEFAULT),
  (gen_random_uuid(), 'Malvern Hills District Council', 1820, DEFAULT),
  (gen_random_uuid(), 'Manchester City Council', 4215, DEFAULT),
  (gen_random_uuid(), 'Mansfield District Council', 3025, DEFAULT),
  (gen_random_uuid(), 'Medway Council', 2280, DEFAULT),
  (gen_random_uuid(), 'Melton Borough Council', 2430, DEFAULT),
  (gen_random_uuid(), 'Merthyr Tydfil County Borough Council', 6925, DEFAULT),
  (gen_random_uuid(), 'Mid Devon District Council', 1135, DEFAULT),
  (gen_random_uuid(), 'Middlesbrough Borough Council', 734, DEFAULT),
  (gen_random_uuid(), 'Mid Suffolk District Council', 3520, DEFAULT),
  (gen_random_uuid(), 'Mid Sussex District Council', 3830, DEFAULT),
  (gen_random_uuid(), 'Milton Keynes City Council', 435, DEFAULT),
  (gen_random_uuid(), 'Mole Valley District Council', 3620, DEFAULT),
  (gen_random_uuid(), 'Monmouthshire County Council', 6840, DEFAULT),
  (gen_random_uuid(), 'Neath Port Talbot County Borough Council', 6930, DEFAULT),
  (gen_random_uuid(), 'Newark and Sherwood District Council', 3030, DEFAULT),
  (gen_random_uuid(), 'Newcastle City Council', 4510, DEFAULT),
  (gen_random_uuid(), 'Newcastle-under-Lyme District Council', 3420, DEFAULT),
  (gen_random_uuid(), 'New Forest District Council', 1740, DEFAULT),
  (gen_random_uuid(), 'Newport City Council', 6935, DEFAULT),
  (gen_random_uuid(), 'Norfolk County Council', 2600, ARRAY[2635,2605,2610,2615,2620,2625,2630]),
  (gen_random_uuid(), 'North Devon Council', 1115, DEFAULT),
  (gen_random_uuid(), 'North East Derbyshire District Council', 1035, DEFAULT),
  (gen_random_uuid(), 'North East Lincolnshire Council', 2002, DEFAULT),
  (gen_random_uuid(), 'North Hertfordshire District Council', 1925, DEFAULT),
  (gen_random_uuid(), 'North Kesteven District Council', 2520, DEFAULT),
  (gen_random_uuid(), 'North Lincolnshire Council', 2003, DEFAULT),
  (gen_random_uuid(), 'North Norfolk District Council', 2620, DEFAULT),
  (gen_random_uuid(), 'North Northamptonshire Council', 2840, DEFAULT),
  (gen_random_uuid(), 'North Somerset Council', 121, DEFAULT),
  (gen_random_uuid(), 'North Tyneside Council', 4515, DEFAULT),
  (gen_random_uuid(), 'Northumberland County Council', 2935, DEFAULT),
  (gen_random_uuid(), 'North Warwickshire Borough Council', 3705, DEFAULT),
  (gen_random_uuid(), 'North West Leicestershire District Council', 2435, DEFAULT),
  (gen_random_uuid(), 'North Yorkshire County Council', 2745, DEFAULT),
  (gen_random_uuid(), 'Norwich City Council', 2625, DEFAULT),
  (gen_random_uuid(), 'Nottingham City Council', 3060, DEFAULT),
  (gen_random_uuid(), 'Nottinghamshire County Council', 3055, ARRAY[3005,3010,3015,3020,3025,3030,3040]),
  (gen_random_uuid(), 'Nuneaton and Bedworth Borough Council', 3710, DEFAULT),
  (gen_random_uuid(), 'Oadby and Wigston Borough Council', 2440, DEFAULT),
  (gen_random_uuid(), 'Oldham Metropolitan Borough Council', 4220, DEFAULT),
  (gen_random_uuid(), 'Oxford City Council', 3110, DEFAULT),
  (gen_random_uuid(), 'Oxfordshire County Council', 3100, ARRAY[3105,3110,3115,3120,3125]),
  (gen_random_uuid(), 'Pembrokeshire County Council', 6845, DEFAULT),
  (gen_random_uuid(), 'Pendle Borough Council', 2340, DEFAULT),
  (gen_random_uuid(), 'Peterborough City Council', 540, DEFAULT),
  (gen_random_uuid(), 'Plymouth City Council', 1160, DEFAULT),
  (gen_random_uuid(), 'Portsmouth City Council', 1775, DEFAULT),
  (gen_random_uuid(), 'Powys County Council', 6850, DEFAULT),
  (gen_random_uuid(), 'Preston City Council', 2345, DEFAULT),
  (gen_random_uuid(), 'Reading Borough Council', 345, DEFAULT),
  (gen_random_uuid(), 'Redcar and Cleveland Borough Council', 728, DEFAULT),
  (gen_random_uuid(), 'Redditch Borough Council', 1825, DEFAULT),
  (gen_random_uuid(), 'Reigate and Banstead Borough Council', 3625, DEFAULT),
  (gen_random_uuid(), 'Rhondda Cynon Taf County Borough Council', 6940, DEFAULT),
  (gen_random_uuid(), 'Ribble Valley Borough Council', 2350, DEFAULT),
  (gen_random_uuid(), 'Rochdale Metropolitan Borough Council', 4225, DEFAULT),
  (gen_random_uuid(), 'Rochford District Council', 1550, DEFAULT),
  (gen_random_uuid(), 'Rossendale Borough Council', 2355, DEFAULT),
  (gen_random_uuid(), 'Rother District Council', 1430, DEFAULT),
  (gen_random_uuid(), 'Rotherham Metropolitan Borough Council', 4415, DEFAULT),
  (gen_random_uuid(), 'Royal Borough of Greenwich', 5330, DEFAULT),
  (gen_random_uuid(), 'Royal Borough of Kensington and Chelsea', 5600, DEFAULT),
  (gen_random_uuid(), 'Royal Borough of Kingston upon Thames', 5630, DEFAULT),
  (gen_random_uuid(), 'Royal Borough of Windsor and Maidenhead', 355, DEFAULT),
  (gen_random_uuid(), 'Rugby Borough Council', 3715, DEFAULT),
  (gen_random_uuid(), 'Runnymede Borough Council', 3630, DEFAULT),
  (gen_random_uuid(), 'Rushcliffe Borough Council', 3040, DEFAULT),
  (gen_random_uuid(), 'Rushmoor Borough Council', 1750, DEFAULT),
  (gen_random_uuid(), 'Rutland County Council', 2470, DEFAULT),
  (gen_random_uuid(), 'Salford City Council', 4230, DEFAULT),
  (gen_random_uuid(), 'Sandwell Metropolitan Borough Council', 4620, DEFAULT),
  (gen_random_uuid(), 'Sefton Metropolitan Borough Council', 4320, DEFAULT),
  (gen_random_uuid(), 'Sevenoaks District Council', 2245, DEFAULT),
  (gen_random_uuid(), 'Sheffield City Council', 4420, DEFAULT),
  (gen_random_uuid(), 'Shropshire Council', 3245, DEFAULT),
  (gen_random_uuid(), 'Slough Borough Council', 350, DEFAULT),
  (gen_random_uuid(), 'Solihull Metropolitan Borough Council', 4625, DEFAULT),
  (gen_random_uuid(), 'Somerset County Council', 3300, DEFAULT),
  (gen_random_uuid(), 'Southampton City Council', 1780, DEFAULT),
  (gen_random_uuid(), 'South Cambridgeshire District Council', 530, DEFAULT),
  (gen_random_uuid(), 'South Derbyshire District Council', 1040, DEFAULT),
  (gen_random_uuid(), 'Southend-on-Sea City Council', 1590, DEFAULT),
  (gen_random_uuid(), 'South Gloucestershire Council', 119, DEFAULT),
  (gen_random_uuid(), 'South Hams District Council', 1125, DEFAULT),
  (gen_random_uuid(), 'South Holland District Council', 2525, DEFAULT),
  (gen_random_uuid(), 'South Kesteven District Council', 2530, DEFAULT),
  (gen_random_uuid(), 'South Norfolk District Council', 2630, DEFAULT),
  (gen_random_uuid(), 'South Oxfordshire District Council', 3115, DEFAULT),
  (gen_random_uuid(), 'South Ribble Borough Council', 2360, DEFAULT),
  (gen_random_uuid(), 'South Staffordshire Council', 3430, DEFAULT),
  (gen_random_uuid(), 'South Tyneside Council', 4520, DEFAULT),
  (gen_random_uuid(), 'Spelthorne Borough Council', 3635, DEFAULT),
  (gen_random_uuid(), 'Stafford Borough Council', 3425, DEFAULT),
  (gen_random_uuid(), 'Staffordshire County Council', 3450, ARRAY[3405,3410,3415,3420,3430,3425,3435,3445]),
  (gen_random_uuid(), 'Staffordshire Moorlands District Council', 3435, DEFAULT),
  (gen_random_uuid(), 'St Albans City and District Council', 1930, DEFAULT),
  (gen_random_uuid(), 'Stevenage Borough Council', 1935, DEFAULT),
  (gen_random_uuid(), 'St Helens Council', 4315, DEFAULT),
  (gen_random_uuid(), 'Stockport Metropolitan Borough Council', 4235, DEFAULT),
  (gen_random_uuid(), 'Stockton-on-Tees Borough Council', 738, DEFAULT),
  (gen_random_uuid(), 'Stoke-on-Trent City Council', 3455, DEFAULT),
  (gen_random_uuid(), 'Stratford-on-Avon District Council', 3720, DEFAULT),
  (gen_random_uuid(), 'Stroud District Council', 1625, DEFAULT),
  (gen_random_uuid(), 'Suffolk County Council', 3500, ARRAY[3505,3540,3515,3520,3545]),
  (gen_random_uuid(), 'Sunderland City Council', 4525, DEFAULT),
  (gen_random_uuid(), 'Surrey County Council', 3600, ARRAY[3605,3610,3615,3620,3625,3630,3635,3640,3645,3650,3655]),
  (gen_random_uuid(), 'Surrey Heath Borough Council', 3640, DEFAULT),
  (gen_random_uuid(), 'Swale Borough Council', 2255, DEFAULT),
  (gen_random_uuid(), 'Swindon Borough Council', 3935, DEFAULT),
  (gen_random_uuid(), 'Tameside Metropolitan Borough Council', 4240, DEFAULT),
  (gen_random_uuid(), 'Tamworth Borough Council', 3445, DEFAULT),
  (gen_random_uuid(), 'Tandridge District Council', 3645, DEFAULT),
  (gen_random_uuid(), 'Teignbridge District Council', 1130, DEFAULT),
  (gen_random_uuid(), 'Telford & Wrekin Council', 3240, DEFAULT),
  (gen_random_uuid(), 'Tendring District Council', 1560, DEFAULT),
  (gen_random_uuid(), 'Test Valley Borough Council', 1760, DEFAULT),
  (gen_random_uuid(), 'Tewkesbury Borough Council', 1630, DEFAULT),
  (gen_random_uuid(), 'Thanet District Council', 2260, DEFAULT),
  (gen_random_uuid(), 'Three Rivers District Council', 1940, DEFAULT),
  (gen_random_uuid(), 'Thurrock Council', 1595, DEFAULT),
  (gen_random_uuid(), 'Tonbridge and Malling Borough Council', 2265, DEFAULT),
  (gen_random_uuid(), 'Torbay Council', 1165, DEFAULT),
  (gen_random_uuid(), 'Torfaen County Borough Council', 6945, DEFAULT),
  (gen_random_uuid(), 'Torridge District Council', 1145, DEFAULT),
  (gen_random_uuid(), 'Trafford Metropolitan Borough Council', 4245, DEFAULT),
  (gen_random_uuid(), 'Tunbridge Wells Borough Council', 2270, DEFAULT),
  (gen_random_uuid(), 'Uttlesford District Council', 1570, DEFAULT),
  (gen_random_uuid(), 'Vale of Glamorgan Council', 6950, DEFAULT),
  (gen_random_uuid(), 'Vale of White Horse District Council', 3120, DEFAULT),
  (gen_random_uuid(), 'Wakefield Metropolitan District Council', 4725, DEFAULT),
  (gen_random_uuid(), 'Walsall Metropolitan Borough Council', 4630, DEFAULT),
  (gen_random_uuid(), 'Warrington Borough Council', 655, DEFAULT),
  (gen_random_uuid(), 'Warwick District Council', 3725, DEFAULT),
  (gen_random_uuid(), 'Warwickshire County Council', 3700, ARRAY[3705,3710,3715,3720,3725]),
  (gen_random_uuid(), 'Watford Borough Council', 1945, DEFAULT),
  (gen_random_uuid(), 'Waverley Borough Council', 3650, DEFAULT),
  (gen_random_uuid(), 'Wealden District Council', 1435, DEFAULT),
  (gen_random_uuid(), 'Welwyn Hatfield Council', 1950, DEFAULT),
  (gen_random_uuid(), 'West Berkshire Council', 340, DEFAULT),
  (gen_random_uuid(), 'West Devon Borough Council', 1150, DEFAULT),
  (gen_random_uuid(), 'West Lancashire Borough Council', 2365, DEFAULT),
  (gen_random_uuid(), 'West Lindsey District Council', 2535, DEFAULT),
  (gen_random_uuid(), 'Westmorland and Furness Council', 935, DEFAULT),
  (gen_random_uuid(), 'West Northamptonshire Council', 2845, DEFAULT),
  (gen_random_uuid(), 'West Oxfordshire District Council', 3125, DEFAULT),
  (gen_random_uuid(), 'West Suffolk District Council', 3545, DEFAULT),
  (gen_random_uuid(), 'West Sussex County Council', 3800, ARRAY[3805,3810,3815,3820,3825,3830,3835]),
  (gen_random_uuid(), 'Wigan Metropolitan Borough Council', 4250, DEFAULT),
  (gen_random_uuid(), 'Wiltshire Council', 3940, DEFAULT),
  (gen_random_uuid(), 'Winchester City Council', 1765, DEFAULT),
  (gen_random_uuid(), 'Wirral Council', 4325, DEFAULT),
  (gen_random_uuid(), 'Woking Borough Council', 3655, DEFAULT),
  (gen_random_uuid(), 'Wokingham Borough Council', 360, DEFAULT),
  (gen_random_uuid(), 'Worcester City Council', 1835, DEFAULT),
  (gen_random_uuid(), 'Worcestershire County Council', 1855, ARRAY[1805,1820,1825,1835,1840,1845]),
  (gen_random_uuid(), 'Worthing Borough Council', 3835, DEFAULT),
  (gen_random_uuid(), 'Wrexham County Borough Council', 6955, DEFAULT),
  (gen_random_uuid(), 'Wychavon District Council', 1840, DEFAULT),
  (gen_random_uuid(), 'Wyre Council', 2370, DEFAULT),
  (gen_random_uuid(), 'Wyre Forest District Council', 1845, DEFAULT);
